plugins {
    id 'application'
    id 'java'
}

group = 'com.reandroid.apkeditor'
version = '1.4.9'

application {
    mainClass = 'com.reandroid.apkeditor.Main'
}

java {
    // Definir la compatibilidad con Java 21
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(files("$rootProject.projectDir/libs/ARSCLib.jar"))
    implementation(files("$rootProject.projectDir/libs/smali.jar"))
    implementation(files("$rootProject.projectDir/libs/JCommand.jar"))
}

processResources {
    filesMatching('apkeditor.properties') {
        expand('version': project.version)
    }
}

javadoc {
    exclude('com/reandroid/test/**')
}

jar {
    exclude('com/reandroid/test/**')
    duplicatesStrategy = DuplicatesStrategy.FAIL
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

// Configuración de FatJar compatible con Gradle 8.x
task fatJar(type: Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveClassifier = 'all'
    
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
    
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    with jar
}

